### ISSUE TITLE
Orianna Bot Grandmaster Role update

### ISSUE THREAD

**Issue by Wylly7** [molenzwiebel/OriannaBot#15]
Hey, idk if this is the right place to say this, but Orianna Bot does not register Grandmaster yet as a role, will this be updated soon?  Whenever a player is grandmaster, the rank role just disappears.  Thanks

**Comment by molenzwiebel** [comment]
Orianna has support for the grandmaster rank, but you will have to add the role yourself (since I do not actually keep track of whether or not servers have rank roles enabled, they are just a preset). 

Here is an example gif for adding the Iron role. Obviously the same process applies for grandmaster:
![](https://cdn.discordapp.com/attachments/329480381055369216/519939687125614592/IdQ60M4jTu.gif)

Do note that you may also need to press the "Create Discord Role" button if you don't already have a grandmaster role on your discord (something I forgot in the gif).
