### ISSUE TITLE
"Unranked" server role doesn't trigger if only playing ARAM?

### ISSUE THREAD

**Issue by m-van-loon** [molenzwiebel/OriannaBot#61]
Unranked
❌ Have a ranked tier of Unranked in your highest ranked queue (excluding TFT)

I play ARAM, TFT and very rarely a bit of coop (to get my first win of the day if all ARAMs end in losses).
I'm guessing that if the API fetch doesn't contain any (PvP?) Summoner's Rift games in its window at all, Ori-bot decides: "nope, you don't qualify for 'Unranked' (anymore)"?

(or is it a clarity issue and is "has never played a game of Summoner's Rift ranked" not (supposed to be) included in "Unranked"?)

**Comment by molenzwiebel** [comment]
This is due to an issue on my end. I recently made it so that people without accounts linked to Orianna will not mistakenly get the "Unranked" role (it doesn't make sense to assign this role without any accounts linked), but it seems I instead made it so that it will ignore anyone without ranks (effectively making the unranked role useless). I just deployed 1eb4ab91c0a18b8deba6eaeb6af62dca9a8b381f which should fix the issue, and you should see an unranked role appear sometime in the next few hours.
